version: 2
registries:
  ft-frontend-saksbehandling: # Gir tilgang til registre innad i nav med ft-frontend-saksbehandling som inngang (PATen bestemmer)
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/ft-frontend-saksbehandling
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: "/"
    registries:
      - ft-frontend-saksbehandling
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10