apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fp-swagger
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: ghcr.io/navikt/fp-swagger:0.21
  port: 9090
  ingresses:
    - "https://fpswagger.dev.intern.nav.no"
  liveness:
    path: /isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isReady
    initialDelay: 5
    timeout: 1
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 800m
      memory: 64Mi
    requests:
      cpu: 500m
      memory: 32Mi
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  webproxy: true
  env:
    - name: HOST
      value: "https://fpswagger.dev.intern.nav.no"
    - name: PORT
      value: "9090"
    - name: REDIS_HOST
      value: "fp-swagger-redis.teamforeldrepenger.svc.nais.local"
    - name: REDIS_PORT
      value: "6379"
    - name: CORS_ALLOWED_HEADERS
      value: "Referer, Origin, Content-Type, Accept, X-Requested-With, cache-control, x_Nav-CallId, pragma, expires"
    - name: CORS_EXPOSED_HEADERS
      value: "Location"
    - name: CORS_ALLOWED_METHODS
      value: "GET, POST, OPTIONS"
    - name: AZURE_APP_LOGOUT_REDIRECT_URL
      value: https://nav.no
    - name: AZURE_APP_REDIRECT_URL
      value: https://fpswagger.dev.intern.nav.no/oauth2/callback
    - name: PROXY_CONFIG
      value: '{"apis":[{"path":"/fpsak/api","url":"http://fpsak","scopes":"api://dev-fss.teamforeldrepenger.fpsak/swagger","name":"fp-sak"},
                       {"path":"/fpabakus/api","url":"http://fpabakus","scopes":"api://dev-fss.teamforeldrepenger.fpabakus/swagger","name":"fp-fpabakus"},
                       {"path":"/fptilbake/api","url":"http://fptilbake","scopes":"api://dev-fss.teamforeldrepenger.fptilbake/swagger","name":"fp-tilbake"},
                       {"path":"/fpfordel/api","url":"http://fpfordel","scopes":"api://dev-fss.teamforeldrepenger.fpfordel/swagger","name":"fp-fordel"},
                       {"path":"/fpformidling/api","url":"http://fpformidling","scopes":"api://dev-fss.teamforeldrepenger.fpformidling/swagger","name":"fp-formidling"},
                       {"path":"/fplos/api","url":"http://fplos","scopes":"api://dev-fss.teamforeldrepenger.fplos/swagger","name":"fp-los"},
                       {"path":"/fprisk/api","url":"http://fprisk","scopes":"api://dev-fss.teamforeldrepenger.fprisk/swagger","name":"fp-risk"},
                       {"path":"/fpoppdrag/api","url":"http://fpoppdrag","scopes":"api://dev-fss.teamforeldrepenger.fpoppdrag/swagger","name":"fp-oppdrag"},
                       {"path":"/fpabonnent/api","url":"http://fpabonnent","scopes":"api://dev-fss.teamforeldrepenger.fpabonnent/swagger","name":"fp-abonnent"},
                       {"path":"/fpinfo/api","url":"http://fpinfo","scopes":"api://dev-fss.teamforeldrepenger.fpinfo/swagger","name":"fp-info"}
              ]}'
  envFrom:
    - secret: redis-password
    - secret: fp-frontend-secrets # cookie sigh and verify
#  accessPolicy:
#    outbound:
#      rules:
#        - application: fpsak-redis

