name: Build and deploy
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
      - "**.MD"
      - ".gitignore"
      - "LICENSE"
jobs:
  build-app:
    name: Build and test
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.generate-build-version.outputs.build-version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # ratchet:pnpm/action-setup@v6

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # ratchet:actions/setup-node@v7.0.0
        with:
          node-version: 26
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'

      - name: Install server dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        working-directory: server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Eslint
        run: pnpm run eslint
        working-directory: server

      - name: Build server
        run: pnpm run build
        working-directory: server

      - name: Generate build version
        id: generate-build-version
        run: |
          echo "build-version=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Print build version
        run: echo "Generated build-version is ${{ steps.generate-build-version.outputs.build-version }}"

      - name: Bygg og push docker image
        if: github.ref_name == 'master'
        uses: navikt/fp-gha-workflows/.github/actions/build-push-docker-image@main
        with:
          build-version: ${{ steps.generate-build-version.outputs.build-version }}
          docker_context: "./server"
          dockerfile: "./server/Dockerfile"
          push-image: ${{ github.ref_name == 'master' }}

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main # ratchet:exclude
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
    secrets: inherit
  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app, deploy-dev]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main # ratchet:exclude
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
    secrets: inherit
