name: Valider pull request

on: [pull_request]
jobs:
  valid-pull-request:
    name: Valider pull request
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v3.0.2
      - name: Sette opp Node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.8.0
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
          cache: 'yarn'

      - name: Installere dependencies
        run: yarn install --ignore-optional --no-progress --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
